# Generated by Django 4.2 on 2024-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("date_naissance", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("mot_de_pass", models.CharField(max_length=50)),
            ],
        ),
    ]
