# Generated by Django 4.2 on 2024-04-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategorieModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="ProduitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(default="produit", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, default="C'est le produit", null=True),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, default="0.99", max_digits=10
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="produit.png", upload_to="produits/"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("mise_a_jour", models.DateTimeField(auto_now=True)),
                ("en_stock", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        default="categorie",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Products.categoriemodel",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Produits",},
        ),
    ]
